# This would be the Argo-CD configmap to set up a ServiceAccount (RBAC)
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    p, role:org-admin, applications, *, */*, allow
    p, role:org-admin, clusters, get, *, allow
    p, role:org-admin, repositories, get, *, allow
    p, role:org-admin, repositories, create, *, allow
    p, role:org-admin, repositories, update, *, allow
    p, role:org-admin, repositories, delete, *, allow
    p, role:org-admin, logs, get, *, allow
    p, role:org-admin, exec, create, */*, allow
    g, org-admin, role:org-admin

    # OIDC configuration as an alternative to dex.
    # oidc.config: |
    #   name: argo-cd
    #   issuer: https://login.microsoftonline.com/TENANT_ID/v2.0
    #   clientID: CLIENT_ID
    #   clientSecret: $oidc.azuread.clientSecret
    #   requestedIDTokenClaims:
    #     groups: org-admin
    #       essential: true
    #   requestedScopes:
    #     - openid
    #     - profile
    #     - email
    ---
    p, role:app-admin, applications, *, */*, allow
    p, role:app-admin, logs, get, *, allow
    p, role:app-admin, exec, create, */*, allow
    g, app-admin, role:app-admin
    ---
    p, role:devops, applications, *, */*, allow
    p, role:devops, clusters, get, *, allow
    p, role:devops, repositories, create, *, allow
    p, role:devops, repositories, update, *, allow
    p, role:devops, repositories, delete, *, allow
    p, role:devops, logs, get, */*, allow
    p, role:devops, exec, create, */*, allow
    g, devops, role:devops
